# Generated by Django 4.2 on 2023-05-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Sginup', '0004_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
