# Generated by Django 4.2 on 2023-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0003_rename_donationrequest_requestdonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdonor',
            name='Patient_Status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
