# Generated by Django 4.2 on 2023-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_requestdonor_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdonor',
            name='drugs',
            field=models.CharField(default='', max_length=255, verbose_name='الادوية اللتي يتناولها المريض'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(verbose_name='تاريخ اخر تبرع'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='requestdonor',
            name='Patient_Status',
            field=models.CharField(max_length=255, verbose_name='حالة المريض'),
        ),
        migrations.AlterField(
            model_name='requestdonor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='requestdonor',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name=' تاريخ عمل الطلب'),
        ),
        migrations.AlterField(
            model_name='requestdonor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='requestdonor',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الموقع'),
        ),
    ]
